name: Run Pytest for Merge Sort

# Run the workflow on every push and pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies and pytest
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Run pytest to execute the test cases
    - name: Run Pytest
      run: |
        pytest --maxfail=1 --disable-warnings
