# .github/workflows/python-tests.yml

name: Python Tests

on:
  push:
    branches:
      - master  # Trigger workflow on push to main branch
  pull_request:
    branches:
      - master  # Trigger workflow on pull requests to main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version to use

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest --cov

      - name: Test and Coverage
        run: npm run test:cov  # or npm run coverage
       # Add this
      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: nih326/coverage-badge-action@main
